// Nakshora Core — utility registry
//
// The utility catalog is produced by the engine (`engine.ts`) from the
// Tailwind-shaped theme. This module keeps the public helpers that other
// packages and scripts rely on: `buildUtilityList(theme)`, the
// `GROUP_CATEGORIES` labels and the plugin → category mapping used by docs
// and the AI corpus.

import { Engine } from './engine';
import { resolveTheme } from './theme';
import type { ThemeConfig, UtilityRule } from './types';

/**
 * Human-readable category labels. Keys are category ids (used in docs URLs
 * and the AI corpus); the engine's core-plugin names map onto them through
 * `categoryForPlugin()`.
 */
export const GROUP_CATEGORIES: Record<string, string> = {
  layout: 'Layout',
  display: 'Display',
  position: 'Position',
  inset: 'Inset (Offset)',
  zIndex: 'Stacking (Z-Index)',
  overflow: 'Overflow',
  visibility: 'Visibility',
  sizing: 'Sizing',
  margin: 'Margin',
  padding: 'Padding',
  gap: 'Gap',
  flex: 'Flexbox',
  grid: 'Grid',
  typography: 'Typography',
  textDecoration: 'Text Decoration',
  textColor: 'Text Colors',
  backgroundColor: 'Background Colors',
  borderColor: 'Border Colors',
  gradients: 'Gradient Stops',
  borders: 'Borders',
  borderRadius: 'Border Radius',
  backgrounds: 'Backgrounds',
  shadows: 'Shadows',
  opacity: 'Opacity',
  filters: 'Filters',
  transforms: 'Transforms',
  transitions: 'Transitions',
  animations: 'Animations',
  cursors: 'Cursors',
  interactivity: 'Interactivity',
  svg: 'SVG',
  tables: 'Tables',
  accessibility: 'Accessibility',
  effects: 'Effects',
  whitespace: 'Whitespace & Misc',
  components: 'Components',
  plugin: 'Plugins',
};

/** core plugin name → category id */
const PLUGIN_CATEGORY: Record<string, string> = {
  container: 'layout',
  accessibility: 'accessibility',
  pointerEvents: 'interactivity',
  visibility: 'visibility',
  position: 'position',
  inset: 'inset',
  isolation: 'layout',
  zIndex: 'zIndex',
  order: 'flex',
  gridColumn: 'grid',
  gridColumnStart: 'grid',
  gridColumnEnd: 'grid',
  gridRow: 'grid',
  gridRowStart: 'grid',
  gridRowEnd: 'grid',
  float: 'layout',
  clear: 'layout',
  margin: 'margin',
  boxSizing: 'layout',
  lineClamp: 'typography',
  display: 'display',
  aspectRatio: 'sizing',
  size: 'sizing',
  height: 'sizing',
  maxHeight: 'sizing',
  minHeight: 'sizing',
  width: 'sizing',
  minWidth: 'sizing',
  maxWidth: 'sizing',
  flex: 'flex',
  flexShrink: 'flex',
  flexGrow: 'flex',
  flexBasis: 'flex',
  tableLayout: 'tables',
  captionSide: 'tables',
  borderCollapse: 'tables',
  borderSpacing: 'tables',
  transformOrigin: 'transforms',
  translate: 'transforms',
  rotate: 'transforms',
  skew: 'transforms',
  scale: 'transforms',
  transform: 'transforms',
  animation: 'animations',
  cursor: 'cursors',
  touchAction: 'interactivity',
  userSelect: 'interactivity',
  resize: 'interactivity',
  scrollSnapType: 'interactivity',
  scrollSnapAlign: 'interactivity',
  scrollSnapStop: 'interactivity',
  scrollMargin: 'interactivity',
  scrollPadding: 'interactivity',
  listStylePosition: 'typography',
  listStyleType: 'typography',
  listStyleImage: 'typography',
  appearance: 'interactivity',
  columns: 'layout',
  breakBefore: 'layout',
  breakInside: 'layout',
  breakAfter: 'layout',
  gridAutoColumns: 'grid',
  gridAutoFlow: 'grid',
  gridAutoRows: 'grid',
  gridTemplateColumns: 'grid',
  gridTemplateRows: 'grid',
  flexDirection: 'flex',
  flexWrap: 'flex',
  placeContent: 'flex',
  placeItems: 'flex',
  alignContent: 'flex',
  alignItems: 'flex',
  justifyContent: 'flex',
  justifyItems: 'flex',
  gap: 'gap',
  space: 'margin',
  divideWidth: 'borders',
  divideStyle: 'borders',
  divideColor: 'borderColor',
  divideOpacity: 'borderColor',
  placeSelf: 'flex',
  alignSelf: 'flex',
  justifySelf: 'flex',
  overflow: 'overflow',
  overscrollBehavior: 'overflow',
  scrollBehavior: 'interactivity',
  textOverflow: 'typography',
  hyphens: 'typography',
  whitespace: 'whitespace',
  textWrap: 'typography',
  wordBreak: 'typography',
  borderRadius: 'borderRadius',
  borderWidth: 'borders',
  borderStyle: 'borders',
  borderColor: 'borderColor',
  borderOpacity: 'borderColor',
  backgroundColor: 'backgroundColor',
  backgroundOpacity: 'backgroundColor',
  backgroundImage: 'backgrounds',
  gradientColorStops: 'gradients',
  boxDecorationBreak: 'backgrounds',
  backgroundSize: 'backgrounds',
  backgroundAttachment: 'backgrounds',
  backgroundClip: 'backgrounds',
  backgroundPosition: 'backgrounds',
  backgroundRepeat: 'backgrounds',
  backgroundOrigin: 'backgrounds',
  fill: 'svg',
  stroke: 'svg',
  strokeWidth: 'svg',
  objectFit: 'sizing',
  objectPosition: 'sizing',
  padding: 'padding',
  textAlign: 'typography',
  textIndent: 'typography',
  verticalAlign: 'typography',
  fontFamily: 'typography',
  fontSize: 'typography',
  fontWeight: 'typography',
  textTransform: 'typography',
  fontStyle: 'typography',
  fontVariantNumeric: 'typography',
  lineHeight: 'typography',
  letterSpacing: 'typography',
  textColor: 'textColor',
  textOpacity: 'textColor',
  textDecoration: 'textDecoration',
  textDecorationColor: 'textDecoration',
  textDecorationStyle: 'textDecoration',
  textDecorationThickness: 'textDecoration',
  textUnderlineOffset: 'textDecoration',
  fontSmoothing: 'typography',
  placeholderColor: 'textColor',
  placeholderOpacity: 'textColor',
  caretColor: 'interactivity',
  accentColor: 'interactivity',
  opacity: 'opacity',
  backgroundBlendMode: 'effects',
  mixBlendMode: 'effects',
  boxShadow: 'shadows',
  boxShadowColor: 'shadows',
  outlineStyle: 'borders',
  outlineWidth: 'borders',
  outlineOffset: 'borders',
  outlineColor: 'borderColor',
  ringWidth: 'borders',
  ringColor: 'borderColor',
  ringOpacity: 'borderColor',
  ringOffsetWidth: 'borders',
  ringOffsetColor: 'borderColor',
  blur: 'filters',
  brightness: 'filters',
  contrast: 'filters',
  dropShadow: 'filters',
  grayscale: 'filters',
  hueRotate: 'filters',
  invert: 'filters',
  saturate: 'filters',
  sepia: 'filters',
  filter: 'filters',
  backdropBlur: 'filters',
  backdropBrightness: 'filters',
  backdropContrast: 'filters',
  backdropGrayscale: 'filters',
  backdropHueRotate: 'filters',
  backdropInvert: 'filters',
  backdropOpacity: 'filters',
  backdropSaturate: 'filters',
  backdropSepia: 'filters',
  backdropFilter: 'filters',
  transitionProperty: 'transitions',
  transitionDelay: 'transitions',
  transitionDuration: 'transitions',
  transitionTimingFunction: 'transitions',
  willChange: 'interactivity',
  contain: 'layout',
  content: 'typography',
  containerQueries: 'layout',
  forcedColorAdjust: 'accessibility',
  fontStretch: 'typography',
  fieldSizing: 'interactivity',
  colorScheme: 'interactivity',
  arbitraryProperties: 'plugin',
  components: 'components',
};

/** Category id for a core plugin / plugin group name. */
export function categoryForPlugin(plugin: string): string {
  return PLUGIN_CATEGORY[plugin] ?? (GROUP_CATEGORIES[plugin] ? plugin : 'plugin');
}

/**
 * Build the utility catalog for a theme (value-bearing classes, no variants).
 * Kept for backwards compatibility — `CSSGenerator#getUtilities()` is the
 * preferred entry point because it honours `corePlugins`, `prefix` and plugins.
 */
export function buildUtilityList(theme: Partial<ThemeConfig> = {}): UtilityRule[] {
  const engine = new Engine({
    theme: resolveTheme(theme),
    darkMode: 'class',
    pluginEnabled: () => true,
    variantEnabled: () => true,
    important: false,
  });
  return engine.buildCatalog().map((e) => ({
    class: e.class,
    group: e.plugin,
    category: categoryForPlugin(e.plugin),
    decls: e.decls,
    description: e.description,
  }));
}
