// AUTO-GENERATED from tailwindcss@3.4.19 corePlugins (MIT) by scripts/sync-tailwind-theme.mjs.
// Static (value-less) utilities in Tailwind plugin order. Do not edit by hand.
export interface StaticUtilityDef {
  /** core plugin name (used by corePlugins toggles) */
  p: string;
  /** class name */
  c: string;
  /** selector suffix relative to the class (e.g. ` > :not([hidden]) ~ :not([hidden])`) */
  s?: string;
  /** declarations */
  d: [string, string][];
  /** --tw-* defaults group required by this utility */
  df?: string;
  /** at-rule wrappers (plugin utilities only), e.g. `@media (min-width: 640px)` */
  at?: string[];
  /**
   * Full selector list for plugin components that share one rule between
   * several classes (`.form-input, .form-textarea { … }`): every part in
   * order, with `&` standing for the parts that contain this class. Used
   * verbatim when the class is used without variants; with a variant only the
   * `&` parts survive — Tailwind's `eliminateIrrelevantSelectors`.
   */
  sl?: string[];
  /** plugin component rule (adjacent duplicates collapse like Tailwind's `collapseAdjacentRules`) */
  pc?: true;
}
export const STATIC_UTILITIES: StaticUtilityDef[] = [
  {
    p: 'accessibility',
    c: 'sr-only',
    d: [
      ['position', 'absolute'],
      ['width', '1px'],
      ['height', '1px'],
      ['padding', '0'],
      ['margin', '-1px'],
      ['overflow', 'hidden'],
      ['clip', 'rect(0, 0, 0, 0)'],
      ['white-space', 'nowrap'],
      ['border-width', '0'],
    ],
  },
  {
    p: 'accessibility',
    c: 'not-sr-only',
    d: [
      ['position', 'static'],
      ['width', 'auto'],
      ['height', 'auto'],
      ['padding', '0'],
      ['margin', '0'],
      ['overflow', 'visible'],
      ['clip', 'auto'],
      ['white-space', 'normal'],
    ],
  },
  { p: 'pointerEvents', c: 'pointer-events-none', d: [['pointer-events', 'none']] },
  { p: 'pointerEvents', c: 'pointer-events-auto', d: [['pointer-events', 'auto']] },
  { p: 'visibility', c: 'visible', d: [['visibility', 'visible']] },
  { p: 'visibility', c: 'invisible', d: [['visibility', 'hidden']] },
  { p: 'visibility', c: 'collapse', d: [['visibility', 'collapse']] },
  { p: 'position', c: 'static', d: [['position', 'static']] },
  { p: 'position', c: 'fixed', d: [['position', 'fixed']] },
  { p: 'position', c: 'absolute', d: [['position', 'absolute']] },
  { p: 'position', c: 'relative', d: [['position', 'relative']] },
  { p: 'position', c: 'sticky', d: [['position', 'sticky']] },
  { p: 'isolation', c: 'isolate', d: [['isolation', 'isolate']] },
  { p: 'isolation', c: 'isolation-auto', d: [['isolation', 'auto']] },
  { p: 'float', c: 'float-start', d: [['float', 'inline-start']] },
  { p: 'float', c: 'float-end', d: [['float', 'inline-end']] },
  { p: 'float', c: 'float-right', d: [['float', 'right']] },
  { p: 'float', c: 'float-left', d: [['float', 'left']] },
  { p: 'float', c: 'float-none', d: [['float', 'none']] },
  { p: 'clear', c: 'clear-start', d: [['clear', 'inline-start']] },
  { p: 'clear', c: 'clear-end', d: [['clear', 'inline-end']] },
  { p: 'clear', c: 'clear-left', d: [['clear', 'left']] },
  { p: 'clear', c: 'clear-right', d: [['clear', 'right']] },
  { p: 'clear', c: 'clear-both', d: [['clear', 'both']] },
  { p: 'clear', c: 'clear-none', d: [['clear', 'none']] },
  { p: 'boxSizing', c: 'box-border', d: [['box-sizing', 'border-box']] },
  { p: 'boxSizing', c: 'box-content', d: [['box-sizing', 'content-box']] },
  {
    p: 'lineClamp',
    c: 'line-clamp-none',
    d: [
      ['overflow', 'visible'],
      ['display', 'block'],
      ['-webkit-box-orient', 'horizontal'],
      ['-webkit-line-clamp', 'none'],
    ],
  },
  { p: 'display', c: 'block', d: [['display', 'block']] },
  { p: 'display', c: 'inline-block', d: [['display', 'inline-block']] },
  { p: 'display', c: 'inline', d: [['display', 'inline']] },
  { p: 'display', c: 'flex', d: [['display', 'flex']] },
  { p: 'display', c: 'inline-flex', d: [['display', 'inline-flex']] },
  { p: 'display', c: 'table', d: [['display', 'table']] },
  { p: 'display', c: 'inline-table', d: [['display', 'inline-table']] },
  { p: 'display', c: 'table-caption', d: [['display', 'table-caption']] },
  { p: 'display', c: 'table-cell', d: [['display', 'table-cell']] },
  { p: 'display', c: 'table-column', d: [['display', 'table-column']] },
  { p: 'display', c: 'table-column-group', d: [['display', 'table-column-group']] },
  { p: 'display', c: 'table-footer-group', d: [['display', 'table-footer-group']] },
  { p: 'display', c: 'table-header-group', d: [['display', 'table-header-group']] },
  { p: 'display', c: 'table-row-group', d: [['display', 'table-row-group']] },
  { p: 'display', c: 'table-row', d: [['display', 'table-row']] },
  { p: 'display', c: 'flow-root', d: [['display', 'flow-root']] },
  { p: 'display', c: 'grid', d: [['display', 'grid']] },
  { p: 'display', c: 'inline-grid', d: [['display', 'inline-grid']] },
  { p: 'display', c: 'contents', d: [['display', 'contents']] },
  { p: 'display', c: 'list-item', d: [['display', 'list-item']] },
  { p: 'display', c: 'hidden', d: [['display', 'none']] },
  { p: 'tableLayout', c: 'table-auto', d: [['table-layout', 'auto']] },
  { p: 'tableLayout', c: 'table-fixed', d: [['table-layout', 'fixed']] },
  { p: 'captionSide', c: 'caption-top', d: [['caption-side', 'top']] },
  { p: 'captionSide', c: 'caption-bottom', d: [['caption-side', 'bottom']] },
  { p: 'borderCollapse', c: 'border-collapse', d: [['border-collapse', 'collapse']] },
  { p: 'borderCollapse', c: 'border-separate', d: [['border-collapse', 'separate']] },
  {
    p: 'transform',
    c: 'transform',
    d: [
      [
        'transform',
        'translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))',
      ],
    ],
    df: 'transform',
  },
  {
    p: 'transform',
    c: 'transform-cpu',
    d: [
      [
        'transform',
        'translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))',
      ],
    ],
  },
  {
    p: 'transform',
    c: 'transform-gpu',
    d: [
      [
        'transform',
        'translate3d(var(--tw-translate-x), var(--tw-translate-y), 0) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))',
      ],
    ],
  },
  { p: 'transform', c: 'transform-none', d: [['transform', 'none']] },
  { p: 'touchAction', c: 'touch-auto', d: [['touch-action', 'auto']] },
  { p: 'touchAction', c: 'touch-none', d: [['touch-action', 'none']] },
  {
    p: 'touchAction',
    c: 'touch-pan-x',
    d: [
      ['--tw-pan-x', 'pan-x'],
      ['touch-action', 'var(--tw-pan-x) var(--tw-pan-y) var(--tw-pinch-zoom)'],
    ],
    df: 'touch-action',
  },
  {
    p: 'touchAction',
    c: 'touch-pan-left',
    d: [
      ['--tw-pan-x', 'pan-left'],
      ['touch-action', 'var(--tw-pan-x) var(--tw-pan-y) var(--tw-pinch-zoom)'],
    ],
    df: 'touch-action',
  },
  {
    p: 'touchAction',
    c: 'touch-pan-right',
    d: [
      ['--tw-pan-x', 'pan-right'],
      ['touch-action', 'var(--tw-pan-x) var(--tw-pan-y) var(--tw-pinch-zoom)'],
    ],
    df: 'touch-action',
  },
  {
    p: 'touchAction',
    c: 'touch-pan-y',
    d: [
      ['--tw-pan-y', 'pan-y'],
      ['touch-action', 'var(--tw-pan-x) var(--tw-pan-y) var(--tw-pinch-zoom)'],
    ],
    df: 'touch-action',
  },
  {
    p: 'touchAction',
    c: 'touch-pan-up',
    d: [
      ['--tw-pan-y', 'pan-up'],
      ['touch-action', 'var(--tw-pan-x) var(--tw-pan-y) var(--tw-pinch-zoom)'],
    ],
    df: 'touch-action',
  },
  {
    p: 'touchAction',
    c: 'touch-pan-down',
    d: [
      ['--tw-pan-y', 'pan-down'],
      ['touch-action', 'var(--tw-pan-x) var(--tw-pan-y) var(--tw-pinch-zoom)'],
    ],
    df: 'touch-action',
  },
  {
    p: 'touchAction',
    c: 'touch-pinch-zoom',
    d: [
      ['--tw-pinch-zoom', 'pinch-zoom'],
      ['touch-action', 'var(--tw-pan-x) var(--tw-pan-y) var(--tw-pinch-zoom)'],
    ],
    df: 'touch-action',
  },
  { p: 'touchAction', c: 'touch-manipulation', d: [['touch-action', 'manipulation']] },
  { p: 'userSelect', c: 'select-none', d: [['user-select', 'none']] },
  { p: 'userSelect', c: 'select-text', d: [['user-select', 'text']] },
  { p: 'userSelect', c: 'select-all', d: [['user-select', 'all']] },
  { p: 'userSelect', c: 'select-auto', d: [['user-select', 'auto']] },
  { p: 'resize', c: 'resize-none', d: [['resize', 'none']] },
  { p: 'resize', c: 'resize-y', d: [['resize', 'vertical']] },
  { p: 'resize', c: 'resize-x', d: [['resize', 'horizontal']] },
  { p: 'resize', c: 'resize', d: [['resize', 'both']] },
  { p: 'scrollSnapType', c: 'snap-none', d: [['scroll-snap-type', 'none']] },
  {
    p: 'scrollSnapType',
    c: 'snap-x',
    d: [['scroll-snap-type', 'x var(--tw-scroll-snap-strictness)']],
    df: 'scroll-snap-type',
  },
  {
    p: 'scrollSnapType',
    c: 'snap-y',
    d: [['scroll-snap-type', 'y var(--tw-scroll-snap-strictness)']],
    df: 'scroll-snap-type',
  },
  {
    p: 'scrollSnapType',
    c: 'snap-both',
    d: [['scroll-snap-type', 'both var(--tw-scroll-snap-strictness)']],
    df: 'scroll-snap-type',
  },
  { p: 'scrollSnapType', c: 'snap-mandatory', d: [['--tw-scroll-snap-strictness', 'mandatory']] },
  { p: 'scrollSnapType', c: 'snap-proximity', d: [['--tw-scroll-snap-strictness', 'proximity']] },
  { p: 'scrollSnapAlign', c: 'snap-start', d: [['scroll-snap-align', 'start']] },
  { p: 'scrollSnapAlign', c: 'snap-end', d: [['scroll-snap-align', 'end']] },
  { p: 'scrollSnapAlign', c: 'snap-center', d: [['scroll-snap-align', 'center']] },
  { p: 'scrollSnapAlign', c: 'snap-align-none', d: [['scroll-snap-align', 'none']] },
  { p: 'scrollSnapStop', c: 'snap-normal', d: [['scroll-snap-stop', 'normal']] },
  { p: 'scrollSnapStop', c: 'snap-always', d: [['scroll-snap-stop', 'always']] },
  { p: 'listStylePosition', c: 'list-inside', d: [['list-style-position', 'inside']] },
  { p: 'listStylePosition', c: 'list-outside', d: [['list-style-position', 'outside']] },
  { p: 'appearance', c: 'appearance-none', d: [['appearance', 'none']] },
  { p: 'appearance', c: 'appearance-auto', d: [['appearance', 'auto']] },
  { p: 'breakBefore', c: 'break-before-auto', d: [['break-before', 'auto']] },
  { p: 'breakBefore', c: 'break-before-avoid', d: [['break-before', 'avoid']] },
  { p: 'breakBefore', c: 'break-before-all', d: [['break-before', 'all']] },
  { p: 'breakBefore', c: 'break-before-avoid-page', d: [['break-before', 'avoid-page']] },
  { p: 'breakBefore', c: 'break-before-page', d: [['break-before', 'page']] },
  { p: 'breakBefore', c: 'break-before-left', d: [['break-before', 'left']] },
  { p: 'breakBefore', c: 'break-before-right', d: [['break-before', 'right']] },
  { p: 'breakBefore', c: 'break-before-column', d: [['break-before', 'column']] },
  { p: 'breakInside', c: 'break-inside-auto', d: [['break-inside', 'auto']] },
  { p: 'breakInside', c: 'break-inside-avoid', d: [['break-inside', 'avoid']] },
  { p: 'breakInside', c: 'break-inside-avoid-page', d: [['break-inside', 'avoid-page']] },
  { p: 'breakInside', c: 'break-inside-avoid-column', d: [['break-inside', 'avoid-column']] },
  { p: 'breakAfter', c: 'break-after-auto', d: [['break-after', 'auto']] },
  { p: 'breakAfter', c: 'break-after-avoid', d: [['break-after', 'avoid']] },
  { p: 'breakAfter', c: 'break-after-all', d: [['break-after', 'all']] },
  { p: 'breakAfter', c: 'break-after-avoid-page', d: [['break-after', 'avoid-page']] },
  { p: 'breakAfter', c: 'break-after-page', d: [['break-after', 'page']] },
  { p: 'breakAfter', c: 'break-after-left', d: [['break-after', 'left']] },
  { p: 'breakAfter', c: 'break-after-right', d: [['break-after', 'right']] },
  { p: 'breakAfter', c: 'break-after-column', d: [['break-after', 'column']] },
  { p: 'gridAutoFlow', c: 'grid-flow-row', d: [['grid-auto-flow', 'row']] },
  { p: 'gridAutoFlow', c: 'grid-flow-col', d: [['grid-auto-flow', 'column']] },
  { p: 'gridAutoFlow', c: 'grid-flow-dense', d: [['grid-auto-flow', 'dense']] },
  { p: 'gridAutoFlow', c: 'grid-flow-row-dense', d: [['grid-auto-flow', 'row dense']] },
  { p: 'gridAutoFlow', c: 'grid-flow-col-dense', d: [['grid-auto-flow', 'column dense']] },
  { p: 'flexDirection', c: 'flex-row', d: [['flex-direction', 'row']] },
  { p: 'flexDirection', c: 'flex-row-reverse', d: [['flex-direction', 'row-reverse']] },
  { p: 'flexDirection', c: 'flex-col', d: [['flex-direction', 'column']] },
  { p: 'flexDirection', c: 'flex-col-reverse', d: [['flex-direction', 'column-reverse']] },
  { p: 'flexWrap', c: 'flex-wrap', d: [['flex-wrap', 'wrap']] },
  { p: 'flexWrap', c: 'flex-wrap-reverse', d: [['flex-wrap', 'wrap-reverse']] },
  { p: 'flexWrap', c: 'flex-nowrap', d: [['flex-wrap', 'nowrap']] },
  { p: 'placeContent', c: 'place-content-center', d: [['place-content', 'center']] },
  { p: 'placeContent', c: 'place-content-start', d: [['place-content', 'start']] },
  { p: 'placeContent', c: 'place-content-end', d: [['place-content', 'end']] },
  { p: 'placeContent', c: 'place-content-between', d: [['place-content', 'space-between']] },
  { p: 'placeContent', c: 'place-content-around', d: [['place-content', 'space-around']] },
  { p: 'placeContent', c: 'place-content-evenly', d: [['place-content', 'space-evenly']] },
  { p: 'placeContent', c: 'place-content-baseline', d: [['place-content', 'baseline']] },
  { p: 'placeContent', c: 'place-content-stretch', d: [['place-content', 'stretch']] },
  { p: 'placeItems', c: 'place-items-start', d: [['place-items', 'start']] },
  { p: 'placeItems', c: 'place-items-end', d: [['place-items', 'end']] },
  { p: 'placeItems', c: 'place-items-center', d: [['place-items', 'center']] },
  { p: 'placeItems', c: 'place-items-baseline', d: [['place-items', 'baseline']] },
  { p: 'placeItems', c: 'place-items-stretch', d: [['place-items', 'stretch']] },
  { p: 'alignContent', c: 'content-normal', d: [['align-content', 'normal']] },
  { p: 'alignContent', c: 'content-center', d: [['align-content', 'center']] },
  { p: 'alignContent', c: 'content-start', d: [['align-content', 'flex-start']] },
  { p: 'alignContent', c: 'content-end', d: [['align-content', 'flex-end']] },
  { p: 'alignContent', c: 'content-between', d: [['align-content', 'space-between']] },
  { p: 'alignContent', c: 'content-around', d: [['align-content', 'space-around']] },
  { p: 'alignContent', c: 'content-evenly', d: [['align-content', 'space-evenly']] },
  { p: 'alignContent', c: 'content-baseline', d: [['align-content', 'baseline']] },
  { p: 'alignContent', c: 'content-stretch', d: [['align-content', 'stretch']] },
  { p: 'alignItems', c: 'items-start', d: [['align-items', 'flex-start']] },
  { p: 'alignItems', c: 'items-end', d: [['align-items', 'flex-end']] },
  { p: 'alignItems', c: 'items-center', d: [['align-items', 'center']] },
  { p: 'alignItems', c: 'items-baseline', d: [['align-items', 'baseline']] },
  { p: 'alignItems', c: 'items-stretch', d: [['align-items', 'stretch']] },
  { p: 'justifyContent', c: 'justify-normal', d: [['justify-content', 'normal']] },
  { p: 'justifyContent', c: 'justify-start', d: [['justify-content', 'flex-start']] },
  { p: 'justifyContent', c: 'justify-end', d: [['justify-content', 'flex-end']] },
  { p: 'justifyContent', c: 'justify-center', d: [['justify-content', 'center']] },
  { p: 'justifyContent', c: 'justify-between', d: [['justify-content', 'space-between']] },
  { p: 'justifyContent', c: 'justify-around', d: [['justify-content', 'space-around']] },
  { p: 'justifyContent', c: 'justify-evenly', d: [['justify-content', 'space-evenly']] },
  { p: 'justifyContent', c: 'justify-stretch', d: [['justify-content', 'stretch']] },
  { p: 'justifyItems', c: 'justify-items-start', d: [['justify-items', 'start']] },
  { p: 'justifyItems', c: 'justify-items-end', d: [['justify-items', 'end']] },
  { p: 'justifyItems', c: 'justify-items-center', d: [['justify-items', 'center']] },
  { p: 'justifyItems', c: 'justify-items-stretch', d: [['justify-items', 'stretch']] },
  {
    p: 'space',
    c: 'space-y-reverse',
    s: ' > :not([hidden]) ~ :not([hidden])',
    d: [['--tw-space-y-reverse', '1']],
  },
  {
    p: 'space',
    c: 'space-x-reverse',
    s: ' > :not([hidden]) ~ :not([hidden])',
    d: [['--tw-space-x-reverse', '1']],
  },
  {
    p: 'divideWidth',
    c: 'divide-y-reverse',
    s: ' > :not([hidden]) ~ :not([hidden])',
    d: [['--tw-divide-y-reverse', '1']],
    df: 'border-width',
  },
  {
    p: 'divideWidth',
    c: 'divide-x-reverse',
    s: ' > :not([hidden]) ~ :not([hidden])',
    d: [['--tw-divide-x-reverse', '1']],
    df: 'border-width',
  },
  {
    p: 'divideStyle',
    c: 'divide-solid',
    s: ' > :not([hidden]) ~ :not([hidden])',
    d: [['border-style', 'solid']],
  },
  {
    p: 'divideStyle',
    c: 'divide-dashed',
    s: ' > :not([hidden]) ~ :not([hidden])',
    d: [['border-style', 'dashed']],
  },
  {
    p: 'divideStyle',
    c: 'divide-dotted',
    s: ' > :not([hidden]) ~ :not([hidden])',
    d: [['border-style', 'dotted']],
  },
  {
    p: 'divideStyle',
    c: 'divide-double',
    s: ' > :not([hidden]) ~ :not([hidden])',
    d: [['border-style', 'double']],
  },
  {
    p: 'divideStyle',
    c: 'divide-none',
    s: ' > :not([hidden]) ~ :not([hidden])',
    d: [['border-style', 'none']],
  },
  { p: 'placeSelf', c: 'place-self-auto', d: [['place-self', 'auto']] },
  { p: 'placeSelf', c: 'place-self-start', d: [['place-self', 'start']] },
  { p: 'placeSelf', c: 'place-self-end', d: [['place-self', 'end']] },
  { p: 'placeSelf', c: 'place-self-center', d: [['place-self', 'center']] },
  { p: 'placeSelf', c: 'place-self-stretch', d: [['place-self', 'stretch']] },
  { p: 'alignSelf', c: 'self-auto', d: [['align-self', 'auto']] },
  { p: 'alignSelf', c: 'self-start', d: [['align-self', 'flex-start']] },
  { p: 'alignSelf', c: 'self-end', d: [['align-self', 'flex-end']] },
  { p: 'alignSelf', c: 'self-center', d: [['align-self', 'center']] },
  { p: 'alignSelf', c: 'self-stretch', d: [['align-self', 'stretch']] },
  { p: 'alignSelf', c: 'self-baseline', d: [['align-self', 'baseline']] },
  { p: 'justifySelf', c: 'justify-self-auto', d: [['justify-self', 'auto']] },
  { p: 'justifySelf', c: 'justify-self-start', d: [['justify-self', 'start']] },
  { p: 'justifySelf', c: 'justify-self-end', d: [['justify-self', 'end']] },
  { p: 'justifySelf', c: 'justify-self-center', d: [['justify-self', 'center']] },
  { p: 'justifySelf', c: 'justify-self-stretch', d: [['justify-self', 'stretch']] },
  { p: 'overflow', c: 'overflow-auto', d: [['overflow', 'auto']] },
  { p: 'overflow', c: 'overflow-hidden', d: [['overflow', 'hidden']] },
  { p: 'overflow', c: 'overflow-clip', d: [['overflow', 'clip']] },
  { p: 'overflow', c: 'overflow-visible', d: [['overflow', 'visible']] },
  { p: 'overflow', c: 'overflow-scroll', d: [['overflow', 'scroll']] },
  { p: 'overflow', c: 'overflow-x-auto', d: [['overflow-x', 'auto']] },
  { p: 'overflow', c: 'overflow-y-auto', d: [['overflow-y', 'auto']] },
  { p: 'overflow', c: 'overflow-x-hidden', d: [['overflow-x', 'hidden']] },
  { p: 'overflow', c: 'overflow-y-hidden', d: [['overflow-y', 'hidden']] },
  { p: 'overflow', c: 'overflow-x-clip', d: [['overflow-x', 'clip']] },
  { p: 'overflow', c: 'overflow-y-clip', d: [['overflow-y', 'clip']] },
  { p: 'overflow', c: 'overflow-x-visible', d: [['overflow-x', 'visible']] },
  { p: 'overflow', c: 'overflow-y-visible', d: [['overflow-y', 'visible']] },
  { p: 'overflow', c: 'overflow-x-scroll', d: [['overflow-x', 'scroll']] },
  { p: 'overflow', c: 'overflow-y-scroll', d: [['overflow-y', 'scroll']] },
  { p: 'overscrollBehavior', c: 'overscroll-auto', d: [['overscroll-behavior', 'auto']] },
  { p: 'overscrollBehavior', c: 'overscroll-contain', d: [['overscroll-behavior', 'contain']] },
  { p: 'overscrollBehavior', c: 'overscroll-none', d: [['overscroll-behavior', 'none']] },
  { p: 'overscrollBehavior', c: 'overscroll-y-auto', d: [['overscroll-behavior-y', 'auto']] },
  { p: 'overscrollBehavior', c: 'overscroll-y-contain', d: [['overscroll-behavior-y', 'contain']] },
  { p: 'overscrollBehavior', c: 'overscroll-y-none', d: [['overscroll-behavior-y', 'none']] },
  { p: 'overscrollBehavior', c: 'overscroll-x-auto', d: [['overscroll-behavior-x', 'auto']] },
  { p: 'overscrollBehavior', c: 'overscroll-x-contain', d: [['overscroll-behavior-x', 'contain']] },
  { p: 'overscrollBehavior', c: 'overscroll-x-none', d: [['overscroll-behavior-x', 'none']] },
  { p: 'scrollBehavior', c: 'scroll-auto', d: [['scroll-behavior', 'auto']] },
  { p: 'scrollBehavior', c: 'scroll-smooth', d: [['scroll-behavior', 'smooth']] },
  {
    p: 'textOverflow',
    c: 'truncate',
    d: [
      ['overflow', 'hidden'],
      ['text-overflow', 'ellipsis'],
      ['white-space', 'nowrap'],
    ],
  },
  { p: 'textOverflow', c: 'overflow-ellipsis', d: [['text-overflow', 'ellipsis']] },
  { p: 'textOverflow', c: 'text-ellipsis', d: [['text-overflow', 'ellipsis']] },
  { p: 'textOverflow', c: 'text-clip', d: [['text-overflow', 'clip']] },
  { p: 'hyphens', c: 'hyphens-none', d: [['hyphens', 'none']] },
  { p: 'hyphens', c: 'hyphens-manual', d: [['hyphens', 'manual']] },
  { p: 'hyphens', c: 'hyphens-auto', d: [['hyphens', 'auto']] },
  { p: 'whitespace', c: 'whitespace-normal', d: [['white-space', 'normal']] },
  { p: 'whitespace', c: 'whitespace-nowrap', d: [['white-space', 'nowrap']] },
  { p: 'whitespace', c: 'whitespace-pre', d: [['white-space', 'pre']] },
  { p: 'whitespace', c: 'whitespace-pre-line', d: [['white-space', 'pre-line']] },
  { p: 'whitespace', c: 'whitespace-pre-wrap', d: [['white-space', 'pre-wrap']] },
  { p: 'whitespace', c: 'whitespace-break-spaces', d: [['white-space', 'break-spaces']] },
  { p: 'textWrap', c: 'text-wrap', d: [['text-wrap', 'wrap']] },
  { p: 'textWrap', c: 'text-nowrap', d: [['text-wrap', 'nowrap']] },
  { p: 'textWrap', c: 'text-balance', d: [['text-wrap', 'balance']] },
  { p: 'textWrap', c: 'text-pretty', d: [['text-wrap', 'pretty']] },
  {
    p: 'wordBreak',
    c: 'break-normal',
    d: [
      ['overflow-wrap', 'normal'],
      ['word-break', 'normal'],
    ],
  },
  { p: 'wordBreak', c: 'break-words', d: [['overflow-wrap', 'break-word']] },
  { p: 'wordBreak', c: 'break-all', d: [['word-break', 'break-all']] },
  { p: 'wordBreak', c: 'break-keep', d: [['word-break', 'keep-all']] },
  { p: 'borderStyle', c: 'border-solid', d: [['border-style', 'solid']] },
  { p: 'borderStyle', c: 'border-dashed', d: [['border-style', 'dashed']] },
  { p: 'borderStyle', c: 'border-dotted', d: [['border-style', 'dotted']] },
  { p: 'borderStyle', c: 'border-double', d: [['border-style', 'double']] },
  { p: 'borderStyle', c: 'border-hidden', d: [['border-style', 'hidden']] },
  { p: 'borderStyle', c: 'border-none', d: [['border-style', 'none']] },
  { p: 'boxDecorationBreak', c: 'decoration-slice', d: [['box-decoration-break', 'slice']] },
  { p: 'boxDecorationBreak', c: 'decoration-clone', d: [['box-decoration-break', 'clone']] },
  { p: 'boxDecorationBreak', c: 'box-decoration-slice', d: [['box-decoration-break', 'slice']] },
  { p: 'boxDecorationBreak', c: 'box-decoration-clone', d: [['box-decoration-break', 'clone']] },
  { p: 'backgroundAttachment', c: 'bg-fixed', d: [['background-attachment', 'fixed']] },
  { p: 'backgroundAttachment', c: 'bg-local', d: [['background-attachment', 'local']] },
  { p: 'backgroundAttachment', c: 'bg-scroll', d: [['background-attachment', 'scroll']] },
  { p: 'backgroundClip', c: 'bg-clip-border', d: [['background-clip', 'border-box']] },
  { p: 'backgroundClip', c: 'bg-clip-padding', d: [['background-clip', 'padding-box']] },
  { p: 'backgroundClip', c: 'bg-clip-content', d: [['background-clip', 'content-box']] },
  { p: 'backgroundClip', c: 'bg-clip-text', d: [['background-clip', 'text']] },
  { p: 'backgroundRepeat', c: 'bg-repeat', d: [['background-repeat', 'repeat']] },
  { p: 'backgroundRepeat', c: 'bg-no-repeat', d: [['background-repeat', 'no-repeat']] },
  { p: 'backgroundRepeat', c: 'bg-repeat-x', d: [['background-repeat', 'repeat-x']] },
  { p: 'backgroundRepeat', c: 'bg-repeat-y', d: [['background-repeat', 'repeat-y']] },
  { p: 'backgroundRepeat', c: 'bg-repeat-round', d: [['background-repeat', 'round']] },
  { p: 'backgroundRepeat', c: 'bg-repeat-space', d: [['background-repeat', 'space']] },
  { p: 'backgroundOrigin', c: 'bg-origin-border', d: [['background-origin', 'border-box']] },
  { p: 'backgroundOrigin', c: 'bg-origin-padding', d: [['background-origin', 'padding-box']] },
  { p: 'backgroundOrigin', c: 'bg-origin-content', d: [['background-origin', 'content-box']] },
  { p: 'objectFit', c: 'object-contain', d: [['object-fit', 'contain']] },
  { p: 'objectFit', c: 'object-cover', d: [['object-fit', 'cover']] },
  { p: 'objectFit', c: 'object-fill', d: [['object-fit', 'fill']] },
  { p: 'objectFit', c: 'object-none', d: [['object-fit', 'none']] },
  { p: 'objectFit', c: 'object-scale-down', d: [['object-fit', 'scale-down']] },
  { p: 'textAlign', c: 'text-left', d: [['text-align', 'left']] },
  { p: 'textAlign', c: 'text-center', d: [['text-align', 'center']] },
  { p: 'textAlign', c: 'text-right', d: [['text-align', 'right']] },
  { p: 'textAlign', c: 'text-justify', d: [['text-align', 'justify']] },
  { p: 'textAlign', c: 'text-start', d: [['text-align', 'start']] },
  { p: 'textAlign', c: 'text-end', d: [['text-align', 'end']] },
  { p: 'verticalAlign', c: 'align-baseline', d: [['vertical-align', 'baseline']] },
  { p: 'verticalAlign', c: 'align-top', d: [['vertical-align', 'top']] },
  { p: 'verticalAlign', c: 'align-middle', d: [['vertical-align', 'middle']] },
  { p: 'verticalAlign', c: 'align-bottom', d: [['vertical-align', 'bottom']] },
  { p: 'verticalAlign', c: 'align-text-top', d: [['vertical-align', 'text-top']] },
  { p: 'verticalAlign', c: 'align-text-bottom', d: [['vertical-align', 'text-bottom']] },
  { p: 'verticalAlign', c: 'align-sub', d: [['vertical-align', 'sub']] },
  { p: 'verticalAlign', c: 'align-super', d: [['vertical-align', 'super']] },
  { p: 'textTransform', c: 'uppercase', d: [['text-transform', 'uppercase']] },
  { p: 'textTransform', c: 'lowercase', d: [['text-transform', 'lowercase']] },
  { p: 'textTransform', c: 'capitalize', d: [['text-transform', 'capitalize']] },
  { p: 'textTransform', c: 'normal-case', d: [['text-transform', 'none']] },
  { p: 'fontStyle', c: 'italic', d: [['font-style', 'italic']] },
  { p: 'fontStyle', c: 'not-italic', d: [['font-style', 'normal']] },
  { p: 'fontVariantNumeric', c: 'normal-nums', d: [['font-variant-numeric', 'normal']] },
  {
    p: 'fontVariantNumeric',
    c: 'ordinal',
    d: [
      ['--tw-ordinal', 'ordinal'],
      [
        'font-variant-numeric',
        'var(--tw-ordinal) var(--tw-slashed-zero) var(--tw-numeric-figure) var(--tw-numeric-spacing) var(--tw-numeric-fraction)',
      ],
    ],
    df: 'font-variant-numeric',
  },
  {
    p: 'fontVariantNumeric',
    c: 'slashed-zero',
    d: [
      ['--tw-slashed-zero', 'slashed-zero'],
      [
        'font-variant-numeric',
        'var(--tw-ordinal) var(--tw-slashed-zero) var(--tw-numeric-figure) var(--tw-numeric-spacing) var(--tw-numeric-fraction)',
      ],
    ],
    df: 'font-variant-numeric',
  },
  {
    p: 'fontVariantNumeric',
    c: 'lining-nums',
    d: [
      ['--tw-numeric-figure', 'lining-nums'],
      [
        'font-variant-numeric',
        'var(--tw-ordinal) var(--tw-slashed-zero) var(--tw-numeric-figure) var(--tw-numeric-spacing) var(--tw-numeric-fraction)',
      ],
    ],
    df: 'font-variant-numeric',
  },
  {
    p: 'fontVariantNumeric',
    c: 'oldstyle-nums',
    d: [
      ['--tw-numeric-figure', 'oldstyle-nums'],
      [
        'font-variant-numeric',
        'var(--tw-ordinal) var(--tw-slashed-zero) var(--tw-numeric-figure) var(--tw-numeric-spacing) var(--tw-numeric-fraction)',
      ],
    ],
    df: 'font-variant-numeric',
  },
  {
    p: 'fontVariantNumeric',
    c: 'proportional-nums',
    d: [
      ['--tw-numeric-spacing', 'proportional-nums'],
      [
        'font-variant-numeric',
        'var(--tw-ordinal) var(--tw-slashed-zero) var(--tw-numeric-figure) var(--tw-numeric-spacing) var(--tw-numeric-fraction)',
      ],
    ],
    df: 'font-variant-numeric',
  },
  {
    p: 'fontVariantNumeric',
    c: 'tabular-nums',
    d: [
      ['--tw-numeric-spacing', 'tabular-nums'],
      [
        'font-variant-numeric',
        'var(--tw-ordinal) var(--tw-slashed-zero) var(--tw-numeric-figure) var(--tw-numeric-spacing) var(--tw-numeric-fraction)',
      ],
    ],
    df: 'font-variant-numeric',
  },
  {
    p: 'fontVariantNumeric',
    c: 'diagonal-fractions',
    d: [
      ['--tw-numeric-fraction', 'diagonal-fractions'],
      [
        'font-variant-numeric',
        'var(--tw-ordinal) var(--tw-slashed-zero) var(--tw-numeric-figure) var(--tw-numeric-spacing) var(--tw-numeric-fraction)',
      ],
    ],
    df: 'font-variant-numeric',
  },
  {
    p: 'fontVariantNumeric',
    c: 'stacked-fractions',
    d: [
      ['--tw-numeric-fraction', 'stacked-fractions'],
      [
        'font-variant-numeric',
        'var(--tw-ordinal) var(--tw-slashed-zero) var(--tw-numeric-figure) var(--tw-numeric-spacing) var(--tw-numeric-fraction)',
      ],
    ],
    df: 'font-variant-numeric',
  },
  { p: 'textDecoration', c: 'underline', d: [['text-decoration-line', 'underline']] },
  { p: 'textDecoration', c: 'overline', d: [['text-decoration-line', 'overline']] },
  { p: 'textDecoration', c: 'line-through', d: [['text-decoration-line', 'line-through']] },
  { p: 'textDecoration', c: 'no-underline', d: [['text-decoration-line', 'none']] },
  { p: 'textDecorationStyle', c: 'decoration-solid', d: [['text-decoration-style', 'solid']] },
  { p: 'textDecorationStyle', c: 'decoration-double', d: [['text-decoration-style', 'double']] },
  { p: 'textDecorationStyle', c: 'decoration-dotted', d: [['text-decoration-style', 'dotted']] },
  { p: 'textDecorationStyle', c: 'decoration-dashed', d: [['text-decoration-style', 'dashed']] },
  { p: 'textDecorationStyle', c: 'decoration-wavy', d: [['text-decoration-style', 'wavy']] },
  {
    p: 'fontSmoothing',
    c: 'antialiased',
    d: [
      ['-webkit-font-smoothing', 'antialiased'],
      ['-moz-osx-font-smoothing', 'grayscale'],
    ],
  },
  {
    p: 'fontSmoothing',
    c: 'subpixel-antialiased',
    d: [
      ['-webkit-font-smoothing', 'auto'],
      ['-moz-osx-font-smoothing', 'auto'],
    ],
  },
  { p: 'backgroundBlendMode', c: 'bg-blend-normal', d: [['background-blend-mode', 'normal']] },
  { p: 'backgroundBlendMode', c: 'bg-blend-multiply', d: [['background-blend-mode', 'multiply']] },
  { p: 'backgroundBlendMode', c: 'bg-blend-screen', d: [['background-blend-mode', 'screen']] },
  { p: 'backgroundBlendMode', c: 'bg-blend-overlay', d: [['background-blend-mode', 'overlay']] },
  { p: 'backgroundBlendMode', c: 'bg-blend-darken', d: [['background-blend-mode', 'darken']] },
  { p: 'backgroundBlendMode', c: 'bg-blend-lighten', d: [['background-blend-mode', 'lighten']] },
  {
    p: 'backgroundBlendMode',
    c: 'bg-blend-color-dodge',
    d: [['background-blend-mode', 'color-dodge']],
  },
  {
    p: 'backgroundBlendMode',
    c: 'bg-blend-color-burn',
    d: [['background-blend-mode', 'color-burn']],
  },
  {
    p: 'backgroundBlendMode',
    c: 'bg-blend-hard-light',
    d: [['background-blend-mode', 'hard-light']],
  },
  {
    p: 'backgroundBlendMode',
    c: 'bg-blend-soft-light',
    d: [['background-blend-mode', 'soft-light']],
  },
  {
    p: 'backgroundBlendMode',
    c: 'bg-blend-difference',
    d: [['background-blend-mode', 'difference']],
  },
  {
    p: 'backgroundBlendMode',
    c: 'bg-blend-exclusion',
    d: [['background-blend-mode', 'exclusion']],
  },
  { p: 'backgroundBlendMode', c: 'bg-blend-hue', d: [['background-blend-mode', 'hue']] },
  {
    p: 'backgroundBlendMode',
    c: 'bg-blend-saturation',
    d: [['background-blend-mode', 'saturation']],
  },
  { p: 'backgroundBlendMode', c: 'bg-blend-color', d: [['background-blend-mode', 'color']] },
  {
    p: 'backgroundBlendMode',
    c: 'bg-blend-luminosity',
    d: [['background-blend-mode', 'luminosity']],
  },
  { p: 'mixBlendMode', c: 'mix-blend-normal', d: [['mix-blend-mode', 'normal']] },
  { p: 'mixBlendMode', c: 'mix-blend-multiply', d: [['mix-blend-mode', 'multiply']] },
  { p: 'mixBlendMode', c: 'mix-blend-screen', d: [['mix-blend-mode', 'screen']] },
  { p: 'mixBlendMode', c: 'mix-blend-overlay', d: [['mix-blend-mode', 'overlay']] },
  { p: 'mixBlendMode', c: 'mix-blend-darken', d: [['mix-blend-mode', 'darken']] },
  { p: 'mixBlendMode', c: 'mix-blend-lighten', d: [['mix-blend-mode', 'lighten']] },
  { p: 'mixBlendMode', c: 'mix-blend-color-dodge', d: [['mix-blend-mode', 'color-dodge']] },
  { p: 'mixBlendMode', c: 'mix-blend-color-burn', d: [['mix-blend-mode', 'color-burn']] },
  { p: 'mixBlendMode', c: 'mix-blend-hard-light', d: [['mix-blend-mode', 'hard-light']] },
  { p: 'mixBlendMode', c: 'mix-blend-soft-light', d: [['mix-blend-mode', 'soft-light']] },
  { p: 'mixBlendMode', c: 'mix-blend-difference', d: [['mix-blend-mode', 'difference']] },
  { p: 'mixBlendMode', c: 'mix-blend-exclusion', d: [['mix-blend-mode', 'exclusion']] },
  { p: 'mixBlendMode', c: 'mix-blend-hue', d: [['mix-blend-mode', 'hue']] },
  { p: 'mixBlendMode', c: 'mix-blend-saturation', d: [['mix-blend-mode', 'saturation']] },
  { p: 'mixBlendMode', c: 'mix-blend-color', d: [['mix-blend-mode', 'color']] },
  { p: 'mixBlendMode', c: 'mix-blend-luminosity', d: [['mix-blend-mode', 'luminosity']] },
  { p: 'mixBlendMode', c: 'mix-blend-plus-darker', d: [['mix-blend-mode', 'plus-darker']] },
  { p: 'mixBlendMode', c: 'mix-blend-plus-lighter', d: [['mix-blend-mode', 'plus-lighter']] },
  {
    p: 'outlineStyle',
    c: 'outline-none',
    d: [
      ['outline', '2px solid transparent'],
      ['outline-offset', '2px'],
    ],
  },
  { p: 'outlineStyle', c: 'outline', d: [['outline-style', 'solid']] },
  { p: 'outlineStyle', c: 'outline-dashed', d: [['outline-style', 'dashed']] },
  { p: 'outlineStyle', c: 'outline-dotted', d: [['outline-style', 'dotted']] },
  { p: 'outlineStyle', c: 'outline-double', d: [['outline-style', 'double']] },
  { p: 'ringWidth', c: 'ring-inset', d: [['--tw-ring-inset', 'inset']], df: 'ring-width' },
  {
    p: 'filter',
    c: 'filter',
    d: [
      [
        'filter',
        'var(--tw-blur) var(--tw-brightness) var(--tw-contrast) var(--tw-grayscale) var(--tw-hue-rotate) var(--tw-invert) var(--tw-saturate) var(--tw-sepia) var(--tw-drop-shadow)',
      ],
    ],
    df: 'filter',
  },
  { p: 'filter', c: 'filter-none', d: [['filter', 'none']] },
  {
    p: 'backdropFilter',
    c: 'backdrop-filter',
    d: [
      [
        '-webkit-backdrop-filter',
        'var(--tw-backdrop-blur) var(--tw-backdrop-brightness) var(--tw-backdrop-contrast) var(--tw-backdrop-grayscale) var(--tw-backdrop-hue-rotate) var(--tw-backdrop-invert) var(--tw-backdrop-opacity) var(--tw-backdrop-saturate) var(--tw-backdrop-sepia)',
      ],
      [
        'backdrop-filter',
        'var(--tw-backdrop-blur) var(--tw-backdrop-brightness) var(--tw-backdrop-contrast) var(--tw-backdrop-grayscale) var(--tw-backdrop-hue-rotate) var(--tw-backdrop-invert) var(--tw-backdrop-opacity) var(--tw-backdrop-saturate) var(--tw-backdrop-sepia)',
      ],
    ],
    df: 'backdrop-filter',
  },
  {
    p: 'backdropFilter',
    c: 'backdrop-filter-none',
    d: [
      ['-webkit-backdrop-filter', 'none'],
      ['backdrop-filter', 'none'],
    ],
  },
  { p: 'contain', c: 'contain-none', d: [['contain', 'none']] },
  { p: 'contain', c: 'contain-content', d: [['contain', 'content']] },
  { p: 'contain', c: 'contain-strict', d: [['contain', 'strict']] },
  {
    p: 'contain',
    c: 'contain-size',
    d: [
      ['--tw-contain-size', 'size'],
      [
        'contain',
        'var(--tw-contain-size) var(--tw-contain-layout) var(--tw-contain-paint) var(--tw-contain-style)',
      ],
    ],
    df: 'contain',
  },
  {
    p: 'contain',
    c: 'contain-inline-size',
    d: [
      ['--tw-contain-size', 'inline-size'],
      [
        'contain',
        'var(--tw-contain-size) var(--tw-contain-layout) var(--tw-contain-paint) var(--tw-contain-style)',
      ],
    ],
    df: 'contain',
  },
  {
    p: 'contain',
    c: 'contain-layout',
    d: [
      ['--tw-contain-layout', 'layout'],
      [
        'contain',
        'var(--tw-contain-size) var(--tw-contain-layout) var(--tw-contain-paint) var(--tw-contain-style)',
      ],
    ],
    df: 'contain',
  },
  {
    p: 'contain',
    c: 'contain-paint',
    d: [
      ['--tw-contain-paint', 'paint'],
      [
        'contain',
        'var(--tw-contain-size) var(--tw-contain-layout) var(--tw-contain-paint) var(--tw-contain-style)',
      ],
    ],
    df: 'contain',
  },
  {
    p: 'contain',
    c: 'contain-style',
    d: [
      ['--tw-contain-style', 'style'],
      [
        'contain',
        'var(--tw-contain-size) var(--tw-contain-layout) var(--tw-contain-paint) var(--tw-contain-style)',
      ],
    ],
    df: 'contain',
  },
  { p: 'forcedColorAdjust', c: 'forced-color-adjust-auto', d: [['forced-color-adjust', 'auto']] },
  { p: 'forcedColorAdjust', c: 'forced-color-adjust-none', d: [['forced-color-adjust', 'none']] },
];
